### PR TITLE
Use Travis for continuous integration

### PR DESCRIPTION
**Pull request by kyllingstad**
Once the project has been activated in Travis, all branches and pull requests will be automatically built and tested (on Linux), allowing us to catch problems before they are merged.

[Here](https://travis-ci.org/kyllingstad/coral) is a demonstration of what it looks like in Travis, based on my personal fork. (In fact, the tests are currently failing!)

### CODE REVIEW

**Comment by mrindar** [comment]
Hm, does this mean that I should not merge this branch? :P

**Comment by kyllingstad** [comment]
Hehe. :-) In this case, it means that it's actually doing what it's supposed to: detecting problems.

**Comment by kyllingstad** [comment]
To clarify, in case there was any doubt: The error reported in the Travis build is unrelated to this pull request, and should be fixed independently.

**Comment by ssadjina** [comment]
Ok, so I have next to no idea what Travis is. But if it builds and tests everything automatically, I can't really see any downside to it either.
I don't really have time to look deeper into this atm. But please let me know if there us anything specific you need my input on. Otherwise, as stated, sounds great , kjør på! :)

**Pull request merged**
